test:
  # Docker is disabled on ***REMOVED*** runner, so image will not work
  # image: continuumio/miniconda3
  # conda should be installed on the ***REMOVED*** runner since 3/21/2019
  #  as /opt/conda/bin/conda
  # following example at https://github.com/conda/conda-gitlab-ci/blob/master/.travis.yml
  script:
    - whoami
    - id
    - pwd
    - echo ${PATH}
    # - ls -lah /opt/conda/bin
    - cat /etc/*release
    # - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    # - bash miniconda.sh -b -p $HOME/miniconda
    # - export PATH="$HOME/miniconda/bin:$PATH"
    # - hash -r
    - /opt/conda/bin/conda --version
    - /opt/conda/bin/conda config --set always_yes yes
    - /opt/conda/bin/conda config --set auto_update_conda False    
    # Do not update, as we don't have permissions:
    # - /opt/conda/bin/conda update -q --all
    # --force option is added in conda 4.6, we're on 4.5.12, so instead try to remove if it's there:
    - env_name="$(pwd)/test_env"
    # - /opt/conda/bin/conda env list
    - /opt/conda/bin/conda remove -p ${env_name} --all || true
    - /opt/conda/bin/conda create -p ${env_name} --file mdcs/nexusLIMS/requirements.txt -c conda-forge
    # - source /opt/conda/bin/activate ${env_name}
    # - cd mdcs/nexusLIMS/tests && pytest --cov=nexusLIMS .
