test:
  # Docker is disabled on ***REMOVED*** runner, so image will not work
  # image: continuumio/miniconda3
  # conda should be installed on the ***REMOVED*** runner since 3/21/2019
  #  as /opt/conda/bin/conda
  # following example at https://github.com/conda/conda-gitlab-ci/blob/master/.travis.yml
  script:
    - echo ${whoami}
    - echo ${id}
    - echo ${PATH}
    - ls -lah /opt/conda/bin
    - cat /etc/*release
    # - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    # - bash miniconda.sh -b -p $HOME/miniconda
    # - export PATH="$HOME/miniconda/bin:$PATH"
    # - hash -r
    - /opt/conda/bin/conda config --set always_yes yes
    - /opt/conda/bin/conda config --set auto_update_conda False    
    - /opt/conda/bin/conda update -q --all
    - /opt/conda/bin/conda create --name test_env --file mdcs/nexusLIMS/requirements.txt
    - source /opt/conda/bin/activate test_env
    - cd mdcs/nexusLIMS/tests && pytest --cov=nexusLIMS .
