# Cache the "test_env" conda environment between jobs
variables:
  CONDA_ENV: "test_env"

cache:
  paths:
    - ${CONDA_ENV}

nexusLIMS_tests:
  script:
    - pipenv run pytest --cov=mdcs/nexusLIMS/nexusLIMS mdcs/nexusLIMS/nexusLIMS/tests
  # Install the environment
  before_script:
    - /opt/conda/bin/conda remove -p ${CONDA_ENV} --all || true
    - echo "Use conda to install the base python environment so we don't mess with system packages"
    - for i in $(seq 1 5); do [ $i -gt 1 ] && echo "Sleeping for 15 seconds..."; sleep 15; /opt/conda/bin/conda create -p ${CONDA_ENV} python=3.7 && s=0 && break || s=$?; done; (exit $s)
    - source /opt/conda/bin/activate $(pwd)/${CONDA_ENV}
    - echo "install pipenv to build the actual environment"
    - pip install pipenv
    - pipenv install --dev

pages:
  script:
    - pipenv run python -m sphinx.cmd.build mdcs/nexusLIMS/doc/source public/doc -n -E -a -j auto -b html
  before_script:
    - source /opt/conda/bin/activate $(pwd)/${CONDA_ENV}
    - pip install pipenv
    - pipenv install --dev
  artifacts:
    paths:
      - public
