image: continuumio/miniconda3

tests:
  stage: test
  script:
    - /opt/conda/bin/conda create --name test_env --file requirements.txt
    - source activate test_env
    - cd mdcs/nexusLIMS/tests && pytest --cov=nexusLIMS .
