image: continuumio/miniconda3:latest

tests:
  stage: test
  script:
    - conda create --name test_env --file requirements.txt
    - source activate test_env
    - cd mdcs/nexusLIMS/tests && pytest --cov=nexusLIMS .
